### ISSUE TITLE
Add Selection for Windows / Linux / MacOS

### ISSUE THREAD

**Issue by liberodark** [ledouxm/cytrus-v6#2]
Hi,

You have select windows in your code : 
![image](https://github.com/ledouxm/cytrus-v6/assets/4238928/18beb02c-883f-4402-ada4-4c6ffc7a5c1f)
Can you add possibility to do selection ?

Best Regards

**Comment by ledouxm** [comment]
I just published a new release (0.0.6) based on this PR #4, you now have the --platform -p argument
